enum Constants {
  SET_USER_ASYNC = 'SET_USER_ASYNC',
  SET_USER = 'SET_USER',
  GET_ALL_PRODUCTS_ASYNC = 'GET_ALL_PRODUCTS_ASYNC',
  GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS',
  SET_PRODUCT_ERROR = 'SET_PRODUCT_ERROR',
}

export default Constants
